name: CI/CD Deployment

on:
  push:
    branches:
      - main  # Déploiement uniquement pour la branche principale

jobs:
  # Job 1: Déploiement du frontend sur Vercel
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utiliser la même version pour checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Configuration de Node.js
        with:
          node-version: '16'  # Ou la version de Node que tu utilises

      - name: Install frontend dependencies
        run: |
          cd src
          npm install

      - name: Build frontend
        run: |
          cd src
          npm run build

      - name: Deploy to Vercel 🌐
        env:
          AUTH_TOKEN_VERCEL: ${{ secrets.AUTH_TOKEN_VERCEL }}
        run: |
          echo "Vercel token: $AUTH_TOKEN_VERCEL"
          npm install -g vercel
          vercel --prod --token $AUTH_TOKEN_VERCEL --yes

  # Job 2: Déploiement du backend sur Render
  deploy_backend:
    runs-on: ubuntu-latest
    needs: deploy_frontend  # Ce job ne démarre que lorsque le job frontend est terminé

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utiliser la même version pour checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-cvokcv3uibrs73bsv350?key=vKoUqfz2XYE






















          
# name: CI/CD Deployment

# on:
#   push:
#     branches:
#       - main  # Déploiement uniquement pour la branche principale

# jobs:
#   # Job 1: Déploiement du frontend sur Vercel
#   deploy_frontend:
#     runs-on: ubuntu-latest
#     steps:
#         - name: Checkout code
#           uses: actions/checkout@v2

#         - name: Set up Python
#           uses: actions/setup-python@v2
#           with:
#             python-version: '3.8'

#         - name: Install dependencies
#           run: |
#             python -m pip install --upgrade pip
#             pip install -r api/requirements.txt

#         - name: Deploy to Vercel 🌐
#           env:
#             AUTH_TOKEN_VERCEL: ${{ secrets.AUTH_TOKEN_VERCEL }}
#           run: |
#             echo "Vercel token: $AUTH_TOKEN_VERCEL"
#             npm install -g vercel
#             vercel --prod --token $AUTH_TOKEN_VERCEL --yes

#   # Job 2: Déploiement du backend sur Render
#   deploy_backend:
#     runs-on: ubuntu-latest
#     needs: deploy_frontend  # Ce job ne démarre que lorsque le job frontend est terminé

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies (backend)
#         run: |
#           cd api
#           python -m pip install --upgrade pip
#           pip install -r api/requirements.txt

#       - name: Deploy to Render
#         run: |
#           curl -X POST https://api.render.com/deploy/srv-cvokcv3uibrs73bsv350?key=vKoUqfz2XYE
